services:
  backend:
    container_name: ourdoc-backend
    image: ourdoc:latest
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/redis/data:/data
      - /home/ubuntu/redis/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
