spring:
  application:
    name: backend
  config:
    import:
      - classpath:secret.yml
      - classpath:ocr.yml


database:
  user:
    name: ${database.name}
    password: ${database.password}
  url: ${database.url}

aws:
  s3:
    bucket-name: ${aws.bucket-name}
    region: ${aws.region}
    access-key: ${aws.access-key}
    secret-key: ${aws.secret-key}
    upload:
      access-url: ${aws.upload.access-url}