spring:
  application:
    name: backend
  config:
    import:
      - classpath:secret.yml
      - classpath:ocr.yml


database:
  user:
    name: ${database.name}
    password: ${database.password}
  url: ${database.url}
