spring:
  ai:
    openai:
      api-key: ${spring-ai.gpt.api-key}
      options:
        model: ${spring-ai.gpt.model}
  application:
    name: backend
  datasource:
    url: ${database.url}
    username: ${database.name}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      timeout: ${redis.timeout}
      password: ${redis.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - classpath:secret.yml
      - classpath:ocr.yml

aws:
  s3:
    bucket-name: ${aws.bucket-name}
    region: ${aws.region}
    access-key: ${aws.access-key}
    secret-key: ${aws.secret-key}
    upload:
      access-url: ${aws.upload.access-url}

book:
  api-url: ${book.nl-api-url}
  cert-key: ${book.nl-cert-key}

logging:
  level:
    root: info
    com.ssafy.ourdoc: debug

school:
  api-url: ${school.elesch-api-url}
  api-key: ${school.elesch-api-key}

openvidu:
  url: ${openvidu.url}
  secret: ${openvidu.secret}
